// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvGGhCWk3BTfsq5waSBql75aWxjc2aleQ',
    appId: '1:342418784411:web:7068135f617fdc417c863e',
    messagingSenderId: '342418784411',
    projectId: 'twiddle-b4eed',
    authDomain: 'twiddle-b4eed.firebaseapp.com',
    storageBucket: 'twiddle-b4eed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYaP68P7R0xp7c6ovrvATfvTYWB7_y0Cc',
    appId: '1:342418784411:android:cada0ce85869847f7c863e',
    messagingSenderId: '342418784411',
    projectId: 'twiddle-b4eed',
    storageBucket: 'twiddle-b4eed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOLbYkDs4yGPWj7rP_U_jefkzMFPtQjlk',
    appId: '1:342418784411:ios:df5c806a179ffd537c863e',
    messagingSenderId: '342418784411',
    projectId: 'twiddle-b4eed',
    storageBucket: 'twiddle-b4eed.appspot.com',
    iosClientId: '342418784411-gpp3785hvge4tc5vdfoe81bmacbqpdo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.twiddle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOLbYkDs4yGPWj7rP_U_jefkzMFPtQjlk',
    appId: '1:342418784411:ios:df5c806a179ffd537c863e',
    messagingSenderId: '342418784411',
    projectId: 'twiddle-b4eed',
    storageBucket: 'twiddle-b4eed.appspot.com',
    iosClientId: '342418784411-gpp3785hvge4tc5vdfoe81bmacbqpdo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.twiddle',
  );
}
